### ISSUE TITLE
Conti - Scraping Error

### ISSUE THREAD

**Issue by GRIT-5ynax** [captainGeech42/ransomwatch#56] opened 2021-06-28 13:45 UTC
**Describe the bug**

Error Message Below:

Traceback (most recent call last):
  File "/app/ransomwatch.py", line 66, in main
    s.scrape_victims()
  File "/app/sites/conti.py", line 56, in scrape_victims
    last_li = page_list.find_all("li")[-1]
AttributeError: 'NoneType' object has no attribute 'find_all'

**To Reproduce**
This error has happened several times over the last 24 hours while ransomwatch has been run on a cron job.

**Expected behavior**
Parse the contents of the Conti site with no errors or have additional error handling built in to handle this error.

**Screenshots**

**Logs**

Traceback (most recent call last):
  File "/app/ransomwatch.py", line 66, in main
    s.scrape_victims()
  File "/app/sites/conti.py", line 56, in scrape_victims
    last_li = page_list.find_all("li")[-1]
AttributeError: 'NoneType' object has no attribute 'find_all'

**Environment**
 - OS: Ubuntu 20.04
 - How you are running it: Docker via cron job (read me best practices implementation)

**Additional context**

**Comment by GRIT-5ynax** [comment] 2021-06-28 13:52
Errors occurred at 3PM and 5PM CT on 6/27/21 and 3AM and 5AM CT on 6/28/21.

**Comment by captainGeech42** [comment] 2021-06-29 02:46
Thank you @GRIT-5ynax for reporting this!

I only see this once in my logs, at 2:10am PDT on June 28th, which aligns with when you saw it. I didn't see it at any of the other times, which makes me think that it was possibly an error by the operators when they added data? Or a site bug perhaps.

Since it's not currently reproducible and the scraper for Conti is working properly still, I am going to close this. But please feel free to open any other issues for scraping issues you have. Thank you!

**Closed by captainGeech42** 2021-06-29 02:46 UTC
